kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dteopen
subjects:
- kind: ServiceAccount
  name: dteopen
  namespace: dteopen
roleRef:
  kind: ClusterRole
  name: dteopen
  apiGroup: rbac.authorization.k8s.io
