apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dteopeninstalloperators.dteopen.example.com
spec:
  group: dteopen.example.com
  names:
    kind: DTEOpenInstallOperator
    listKind: DTEOpenInstallOperatorList
    plural: dteopeninstalloperators
    singular: dteopeninstalloperator
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
