apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "dteopen.example.com/v1alpha1",
          "kind": "DTEOpenAssignCluster",
          "metadata": {
            "name": "dteopenassigncluster-user-ibmcloudlite01-cluster-01"
          },
          "spec": {
            "email": "ibmcloudlite01@gmail.com"
          }
        },
        {
          "apiVersion": "dteopen.example.com/v1alpha1",
          "kind": "DTEOpenInstallOperator",
          "metadata": {
            "name": "dteopeninstalloperator-user-ibmcloudlite01-cluster-01"
          },
          "spec": {
            "clusterId": "bpkq9dld02l8muj8fdr0",
            "operatorUrl": "https://operatorhub.io/install/redis-enterprise.yaml"
          }
        },
        {
          "apiVersion": "dteopen.example.com/v1alpha1",
          "kind": "DTEOpenGetClusterStatus",
          "metadata": {
            "name": "dteopengetclusterstatus-user-ibmcloudlite01-cluster-01"
          },
          "spec": {
            "email": "ibmcloudlite01@gmail.com",
            "clusterId": "bpkq9dld02l8muj8fdr0"
          }
        }
      ]
    capabilities: Basic Install
  name: dteopen-operator.v0.0.1
  namespace: dteopen
spec:
  description: DTEOpen Operator
  displayName: Dteopen Operator
  keywords: ['DTE-Open', 'operator', 'ocp', '4.3']

  maintainers:
  - name: CoreOS, Inc
    email: support@coreos.com

  provider:
    name: Openlabs

  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: DTEOpenAssignCluster
      name: dteopenassignclusters.dteopen.example.com
      version: v1alpha1
      description: Assign Cluster
      displayName: Assign Cluster
    - kind: DTEOpenInstallOperator
      name: dteopeninstalloperators.dteopen.example.com
      version: v1alpha1
      description: Install Operator
      displayName: Install Operator
    - kind: DTEOpenGetClusterStatus
      name: dteopengetclusterstatus.dteopen.example.com
      version: v1alpha1
      description: Get Cluster Status
      displayName: Get Cluster Status
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - dteopen
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - dteopen.example.com
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - '*'
        serviceAccountName: dteopen
      deployments:
      - name: dteopen
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: dteopen
          strategy: {}
          template:
            metadata:
              labels:
                name: dteopen
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/deekshah86/dteopen
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: dteopen
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/deekshah86/dteopen
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: dteopen
              volumes:
              - emptyDir: {}
                name: runner
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: dteopen-operator.v0.0.0
  version: 0.0.1
